# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == 'main'
   
stages:
  - check
  - build
  - test

variables:
  NEXUS_CI_GO_VERSION: "1.26.1"  
  NEXUS_CI_DEBIAN_VERSION: "trixie"
  NEXUS_CI_DEFAULT_PYTHON_VER: "3.13"
  NEXUS_CI_RUST_VERSION: "1.94.0"
  NEXUS_CI_NODE_VERSION: "24"
  NEXUS_CI_NVM_VERSION: "0.40.4"
  NEXUS_CI_UV_VERSION: "0.9.28"
  NEXUS_CI_WASM_VERSION: "0.2.20"
  NEXUS_CI_WORKSPACE_TMP: "${CI_PROJECT_DIR}/.tmp"
  UV_CACHE_DIR: .uv-cache
  UV_INSTALL_DIR: /usr/local/bin
  UV_PYTHON_DOWNLOADS: never

default:
  cache:
    - key: $CI_COMMIT_REF_SLUG
      paths:
        - $UV_CACHE_DIR
  before_script:
    - mkdir -p ${NEXUS_CI_WORKSPACE_TMP}

check:precommit:
  stage: check
  image:
    name: ghcr.io/astral-sh/uv:${NEXUS_CI_UV_VERSION}-python${NEXUS_CI_DEFAULT_PYTHON_VER}-${NEXUS_CI_DEBIAN_VERSION}
    pull_policy: if-not-present
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    - key:
        files:
          - .pre-commit-config.yaml
      paths:
        - ${CI_PROJECT_DIR}/.cache/pre-commit
  script:
    - echo "Running pre-commit"
    - uv venv --python=${NEXUS_CI_DEFAULT_PYTHON_VER} --seed ${NEXUS_CI_WORKSPACE_TMP}/.venv
    - source ${NEXUS_CI_WORKSPACE_TMP}/.venv/bin/activate
    - uv sync --active --only-dev
    - git reset --hard
    - pre-commit run --show-diff-on-failure
  after_script:
    - uv cache prune --ci

  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  cache:
    key:
      files:
        - .pre-commit-config.yaml
    paths:
      - .cache/pre-commit
  after_script:
    - uv cache prune --ci

build:
  stage: build
  image:
    name: rust:${NEXUS_CI_RUST_VERSION}-${NEXUS_CI_DEBIAN_VERSION}
    pull_policy: if-not-present
  artifacts:
    name: "cargo-build"
    when: on_success
    paths:
      - target/
      - crates/wasm/pkg/
      - python/nat_nexus/*.so
  script:
    - echo "Installing build tools"
    - apt-get update -qq && apt-get install -y --no-install-recommends build-essential
    - echo "Installing uv & Python"
    - curl -LsSf https://astral.sh/uv/${NEXUS_CI_UV_VERSION}/install.sh | sh
    - UV_PYTHON_DOWNLOADS=manual uv python install --managed-python ${NEXUS_CI_DEFAULT_PYTHON_VER}
    - export PYO3_PYTHON=$(uv python find --managed-python ${NEXUS_CI_DEFAULT_PYTHON_VER})
    - echo "Building Nexus"
    - cargo build --release --workspace
    - cargo test --no-run --release --workspace
    - echo "Building Python Extension"
    - uv venv --python=${NEXUS_CI_DEFAULT_PYTHON_VER} --seed ${NEXUS_CI_WORKSPACE_TMP}/.venv
    - source ${NEXUS_CI_WORKSPACE_TMP}/.venv/bin/activate
    - uv sync --active --reinstall-package nvidia-nat-nexus
    - echo "Building WASM package"
    - cargo install wasm-pack
    - wasm-pack build --release crates/wasm
  after_script:
    - uv cache prune --ci

# Test stages are listed  in alphabetical order
test:go_tests:
  stage: test
  timeout: 30 minutes
  image:
    name: golang:${NEXUS_CI_GO_VERSION}-${NEXUS_CI_DEBIAN_VERSION}
    pull_policy: if-not-present
  needs:
    - job: build
  artifacts:
    when: always
    reports:
      junit: go_junit_report.xml
      coverage_report:
        coverage_format: cobertura
        path: go_coverage_report.xml
  variables:
    CGO_LDFLAGS: "-L${CI_PROJECT_DIR}/target/release"
    LD_LIBRARY_PATH: "${CI_PROJECT_DIR}/target/release"
  script:
      - echo "Go Versions:"
      - go version
      - cd go/nat_nexus
      - echo "Installing Go test reporting tools"
      - go install github.com/jstemmer/go-junit-report/v2@latest
      - go install github.com/boumenot/gocover-cobertura@latest
      - echo "Running Go tests:"
      - go test -v -coverprofile=coverage.out ./... 2>&1
          | tee /dev/stderr
          | go-junit-report -set-exit-code > ${CI_PROJECT_DIR}/go_junit_report.xml
      - gocover-cobertura < coverage.out > ${CI_PROJECT_DIR}/go_coverage_report.xml

test:nodejs_tests:
  stage: test
  timeout: 30 minutes
  image:
    name: rust:${NEXUS_CI_RUST_VERSION}-${NEXUS_CI_DEBIAN_VERSION}
    pull_policy: if-not-present
  needs:
    - job: build
  artifacts:
    when: always
    reports:
      junit: nodejs_junit.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura-coverage.xml
  script:
    - echo "Installing NodeJS"
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NEXUS_CI_NVM_VERSION}/install.sh | bash
    - \. "$HOME/.nvm/nvm.sh"
    - nvm install ${NEXUS_CI_NODE_VERSION}
    - echo "NodeJS and NPM versions:"
    - node --version && npm --version
    - echo "Installing test dependencies"
    - cd crates/node && npm install && npm install -g c8 && npm run build && cd ../..
    - echo "Running NodeJS tests"
    - c8 --reporter=cobertura --reports-dir=${CI_PROJECT_DIR}
        node --test
        --test-reporter=spec --test-reporter-destination=stdout
        --test-reporter=junit --test-reporter-destination=${CI_PROJECT_DIR}/nodejs_junit.xml
        crates/node/tests/*.mjs

test:python_tests:
  stage: test
  timeout: 30 minutes
  image:
    name: ghcr.io/astral-sh/uv:${NEXUS_CI_UV_VERSION}-python${NEXUS_CI_DEFAULT_PYTHON_VER}-${NEXUS_CI_DEBIAN_VERSION}
    pull_policy: if-not-present
  needs:
    - job: build
  coverage: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    when: always
    reports:
      junit: pytest_junit_report*.xml
      coverage_report:
        coverage_format: cobertura  # or jacoco
        path: pytest_coverage_report*.xml
  after_script:
    - uv cache prune --ci
  script:
    - echo "Creating UV environment"
    - uv venv --python=${NEXUS_CI_DEFAULT_PYTHON_VER} --seed ${WORKSPACE_TMP}/.venv
    - source ${WORKSPACE_TMP}/.venv/bin/activate
    - uv sync --active
    - echo "Running Python tests"
    - pytest
        --cov=nat_nexus --cov-report term-missing
        --junit-xml=${CI_PROJECT_DIR}/pytest_junit_report.xml
        --cov-report xml:${CI_PROJECT_DIR}/pytest_coverage_report.xml

test:rust_tests:
  stage: test
  timeout: 30 minutes
  image:
    name: rust:${NEXUS_CI_RUST_VERSION}-${NEXUS_CI_DEBIAN_VERSION}
    pull_policy: if-not-present
  needs:
    - job: build
  artifacts:
    when: always
    reports:
      junit: target/nextest/ci/rust_junit_report.xml
  script:
    - echo "Installing build tools"
    - apt-get update -qq && apt-get install -y --no-install-recommends build-essential
    - echo "Installing uv & Python"
    - curl -LsSf https://astral.sh/uv/${NEXUS_CI_UV_VERSION}/install.sh | sh
    - UV_PYTHON_DOWNLOADS=manual uv python install --managed-python ${NEXUS_CI_DEFAULT_PYTHON_VER}
    - export PYO3_PYTHON=$(uv python find --managed-python ${NEXUS_CI_DEFAULT_PYTHON_VER})
    - echo "Installing cargo-nextest"
    - cargo install cargo-nextest --locked
    - echo "Running Rust tests"
    - cargo nextest run --workspace --release --profile ci

test:wasm_tests:
  stage: test
  timeout: 30 minutes
  image:
    name: rust:${NEXUS_CI_RUST_VERSION}-${NEXUS_CI_DEBIAN_VERSION}
    pull_policy: if-not-present
  needs:
    - job: build
  script:
    - echo "Installing NodeJS"
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NEXUS_CI_NVM_VERSION}/install.sh | bash
    - \. "$HOME/.nvm/nvm.sh"
    - nvm install ${NEXUS_CI_NODE_VERSION}
    - echo "NodeJS and NPM versions:"
    - node --version && npm --version
    - echo "Installing wasm-pack"
    - cargo install wasm-pack
    - echo "Running WASM tests"
    - wasm-pack test --release --node crates/wasm
