sonar.projectKey=GPUSW_SW_SW_NeMo-Flow
sonar.go.coverage.reportPaths=.sonar-reports/go_coverage.out
sonar.javascript.lcov.reportPaths=.sonar-reports/nodejs_lcov.info,.sonar-reports/wasm_lcov.info
sonar.python.coverage.reportPaths=.sonar-reports/pytest_coverage_report.xml
sonar.rust.cobertura.reportPaths=.sonar-reports/rust_coverage_report.xml
