# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Type stubs for ``nemo_relay.pii_rampart``."""

from dataclasses import dataclass, field
from typing import Literal, TypedDict

from nemo_relay import JsonObject
from nemo_relay.plugin import ConfigDiagnostic, ConfigPolicy

class ConfigReport(TypedDict):
    diagnostics: list[ConfigDiagnostic]

@dataclass(slots=True)
class RampartPiiConfig:
    model_path: str
    version: int = ...
    input: bool = ...
    output: bool = ...
    mark: bool = ...
    tool_input: bool = ...
    tool_output: bool = ...
    priority: int = ...
    codec: Literal["openai_chat", "openai_responses", "anthropic_messages"] | str | None = ...
    target_paths: list[str] = field(default_factory=list)
    target_path_patterns: list[str] = field(default_factory=list)
    min_score: float = ...
    excluded_labels: list[str] = field(default_factory=list)
    replacement: str = ...
    max_windows_per_payload: int = ...
    inference_batch_size: int = ...
    policy: ConfigPolicy = field(default_factory=ConfigPolicy)
    def to_dict(self) -> JsonObject: ...

RAMPART_PII_PLUGIN_KIND: Literal["pii_rampart"]
RAMPART_MODEL_ID: Literal["nationaldesignstudio/rampart"]
RAMPART_MODEL_REVISION: Literal["b1993e4e68b082835b80ffc65acc03325ea2e501"]

@dataclass(slots=True)
class ComponentSpec:
    config: RampartPiiConfig | JsonObject
    enabled: bool = ...
    def to_dict(self) -> JsonObject: ...

def validate_config(config: RampartPiiConfig | JsonObject) -> ConfigReport: ...
