/* NVAgentRT C API - Auto-generated by cbindgen. Do not edit. */

#ifndef NVAGENTRT_H
#define NVAGENTRT_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * The type of lifecycle event emitted by the runtime.
 */
enum NvAgentRtEventType {
  /**
   * A scope or operation has started.
   */
  NV_AGENT_RT_EVENT_TYPE_START = 0,
  /**
   * A scope or operation has ended.
   */
  NV_AGENT_RT_EVENT_TYPE_END = 1,
  /**
   * A point-in-time marker event.
   */
  NV_AGENT_RT_EVENT_TYPE_MARK = 2,
};
typedef int32_t NvAgentRtEventType;

/**
 * The type of scope in the agent execution hierarchy.
 */
enum NvAgentRtScopeType {
  /**
   * Top-level agent scope.
   */
  NV_AGENT_RT_SCOPE_TYPE_AGENT = 0,
  /**
   * Generic function scope.
   */
  NV_AGENT_RT_SCOPE_TYPE_FUNCTION = 1,
  /**
   * Tool invocation scope.
   */
  NV_AGENT_RT_SCOPE_TYPE_TOOL = 2,
  /**
   * LLM call scope.
   */
  NV_AGENT_RT_SCOPE_TYPE_LLM = 3,
  /**
   * Retriever scope (e.g., RAG lookup).
   */
  NV_AGENT_RT_SCOPE_TYPE_RETRIEVER = 4,
  /**
   * Embedder scope.
   */
  NV_AGENT_RT_SCOPE_TYPE_EMBEDDER = 5,
  /**
   * Reranker scope.
   */
  NV_AGENT_RT_SCOPE_TYPE_RERANKER = 6,
  /**
   * Guardrail evaluation scope.
   */
  NV_AGENT_RT_SCOPE_TYPE_GUARDRAIL = 7,
  /**
   * Evaluator scope.
   */
  NV_AGENT_RT_SCOPE_TYPE_EVALUATOR = 8,
  /**
   * User-defined custom scope.
   */
  NV_AGENT_RT_SCOPE_TYPE_CUSTOM = 9,
  /**
   * Unknown or unspecified scope type.
   */
  NV_AGENT_RT_SCOPE_TYPE_UNKNOWN = 10,
};
typedef int32_t NvAgentRtScopeType;

/**
 * Status codes returned by all FFI functions.
 *
 * Every `extern "C"` function in this library returns an `NvAgentRtStatus`.
 * On non-`Ok` returns, call [`nvagentrt_last_error`] on the same thread to
 * retrieve a human-readable error message.
 */
enum NvAgentRtStatus {
  /**
   * Operation completed successfully.
   */
  NV_AGENT_RT_STATUS_OK = 0,
  /**
   * A resource with the given name already exists.
   */
  NV_AGENT_RT_STATUS_ALREADY_EXISTS = 1,
  /**
   * The requested resource was not found.
   */
  NV_AGENT_RT_STATUS_NOT_FOUND = 2,
  /**
   * The scope stack is empty (no active scope).
   */
  NV_AGENT_RT_STATUS_SCOPE_STACK_EMPTY = 3,
  /**
   * A guardrail rejected the operation.
   */
  NV_AGENT_RT_STATUS_GUARDRAIL_REJECTED = 4,
  /**
   * An internal runtime error occurred.
   */
  NV_AGENT_RT_STATUS_INTERNAL = 5,
  /**
   * A required pointer argument was null.
   */
  NV_AGENT_RT_STATUS_NULL_POINTER = 6,
  /**
   * A JSON string argument could not be parsed.
   */
  NV_AGENT_RT_STATUS_INVALID_JSON = 7,
  /**
   * A C string argument contained invalid UTF-8.
   */
  NV_AGENT_RT_STATUS_INVALID_UTF8 = 8,
};
typedef int32_t NvAgentRtStatus;

/**
 * Opaque ATIF exporter handle.
 */
typedef struct FfiAtifExporter FfiAtifExporter;

/**
 * Opaque wrapper around a lifecycle event emitted by the runtime.
 */
typedef struct FfiEvent FfiEvent;

/**
 * Opaque handle representing an active LLM call.
 */
typedef struct FfiLLMHandle FfiLLMHandle;

/**
 * Opaque wrapper around an LLM request (headers, content).
 */
typedef struct FfiLLMRequest FfiLLMRequest;

/**
 * Opaque wrapper around an LLM response (data).
 */
typedef struct FfiLLMResponse FfiLLMResponse;

/**
 * Opaque handle representing an active execution scope.
 */
typedef struct FfiScopeHandle FfiScopeHandle;

/**
 * Opaque handle to an isolated scope stack for per-request/per-task isolation.
 */
typedef struct FfiScopeStack FfiScopeStack;

/**
 * Opaque stream handle for consuming LLM streaming responses chunk by chunk.
 * Use `nvagentrt_stream_next` to poll and `nvagentrt_stream_free` to release.
 */
typedef struct FfiStream FfiStream;

/**
 * Opaque handle representing an active tool call.
 */
typedef struct FfiToolHandle FfiToolHandle;

typedef struct Option_NvAgentRtCollectorCb Option_NvAgentRtCollectorCb;

typedef struct Option_NvAgentRtFinalizerCb Option_NvAgentRtFinalizerCb;

typedef struct Option_NvAgentRtJsonCb Option_NvAgentRtJsonCb;

/**
 * Callback for tool execution (default callable). Receives arguments as JSON,
 * returns result as JSON. The returned string must be allocated with `malloc`
 * or equivalent.
 */
typedef char *(*NvAgentRtToolExecCb)(void *user_data, const char *args_json);

/**
 * Optional destructor for user data passed to callbacks.
 * Called when the runtime no longer needs the associated callback.
 */
typedef void (*NvAgentRtFreeFn)(void *user_data);

/**
 * Callback for LLM execution (default callable). Receives a native JSON C string,
 * returns the response as a JSON C string.
 */
typedef char *(*NvAgentRtLlmExecCb)(void *user_data, const char *native_json);

/**
 * Callback for tool conditional execution guardrails.
 * Receives tool name and arguments as JSON.
 * Returns NULL to allow execution, or an error message string to reject.
 */
typedef char *(*NvAgentRtToolConditionalCb)(void *user_data, const char *name, const char *args_json);

/**
 * Callback for tool execution intercept conditions.
 * Receives tool name and arguments as JSON.
 * Returns `true` if this intercept should handle the execution.
 */
typedef bool (*NvAgentRtToolExecConditionalCb)(void *user_data,
                                               const char *name,
                                               const char *args_json);

/**
 * Runtime-provided "next" callback for tool execution middleware chain.
 * Call this from an intercept to invoke the next layer (or original function).
 * `next_ctx` is an opaque pointer managed by the runtime.
 */
typedef char *(*NvAgentRtToolExecNextFn)(const char *args_json, void *next_ctx);

/**
 * Callback for tool execution intercepts. Receives arguments as JSON plus
 * a `next` callback and its context. Call `next_fn(args, next_ctx)` to invoke
 * the next layer in the middleware chain, or return directly to short-circuit.
 */
typedef char *(*NvAgentRtToolExecInterceptCb)(void *user_data,
                                              const char *args_json,
                                              NvAgentRtToolExecNextFn next_fn,
                                              void *next_ctx);

/**
 * Callback for LLM request sanitization. Receives an `FfiLLMRequest` and returns
 * a new (possibly modified) `FfiLLMRequest`. Return null to use defaults.
 */
typedef struct FfiLLMRequest *(*NvAgentRtLlmRequestCb)(void *user_data,
                                                       const struct FfiLLMRequest *request);

/**
 * Generic JSON-to-JSON callback, used for LLM response sanitization and intercepts.
 * The returned string must be allocated with `malloc` or equivalent.
 */
typedef char *(*NvAgentRtJsonCb)(void *user_data, const char *json);

/**
 * Callback for LLM conditional execution guardrails.
 * Returns NULL to allow execution, or an error message string to reject.
 */
typedef char *(*NvAgentRtLlmConditionalCb)(void *user_data, const struct FfiLLMRequest *request);

/**
 * Callback for SSE stream response intercepts. Receives the SSE event serialized
 * as a JSON C string and returns a (possibly modified) JSON C string.
 */
typedef char *(*NvAgentRtSseInterceptCb)(void *user_data, const char *sse_json);

/**
 * Callback for LLM execution intercept conditions.
 * Receives native JSON string. Returns `true` if this intercept should handle the execution.
 */
typedef bool (*NvAgentRtLlmExecConditionalCb)(void *user_data, const char *native_json);

/**
 * Runtime-provided "next" callback for LLM execution middleware chain.
 * Takes a native JSON C string, returns a response JSON C string.
 */
typedef char *(*NvAgentRtLlmExecNextFn)(const char *native_json, void *next_ctx);

/**
 * Callback for LLM execution intercepts with middleware chain support.
 * Receives native JSON C string plus a `next` callback and its context.
 */
typedef char *(*NvAgentRtLlmExecInterceptCb)(void *user_data,
                                             const char *native_json,
                                             NvAgentRtLlmExecNextFn next_fn,
                                             void *next_ctx);

/**
 * Callback for event subscribers. Invoked on each lifecycle event emitted by
 * the runtime. The `FfiEvent` pointer is only valid for the duration of the call.
 */
typedef void (*NvAgentRtEventSubscriberCb)(void *user_data, const struct FfiEvent *event);

/**
 * Retrieve the current scope handle from the thread-local scope stack.
 *
 * # Parameters
 * - `out`: On success, receives a heap-allocated `FfiScopeHandle` that must be
 *   freed with `nvagentrt_scope_handle_free`.
 *
 * # Safety
 * `out` must be a valid, non-null pointer.
 */
NvAgentRtStatus nvagentrt_get_handle(struct FfiScopeHandle **out);

/**
 * Push a new scope onto the scope stack.
 *
 * # Parameters
 * - `name`: Null-terminated scope name.
 * - `scope_type`: The type of scope to create.
 * - `parent`: Optional parent scope handle, or null for auto-parenting.
 * - `attributes`: Bitfield of scope attributes.
 * - `out`: On success, receives a heap-allocated `FfiScopeHandle`.
 *
 * # Safety
 * `name` must be a valid C string. `out` must be non-null. `parent` may be null.
 */
NvAgentRtStatus nvagentrt_push_scope(const char *name,
                                     NvAgentRtScopeType scope_type,
                                     const struct FfiScopeHandle *parent,
                                     uint32_t attributes,
                                     struct FfiScopeHandle **out);

/**
 * Pop a scope from the scope stack by its handle.
 *
 * # Parameters
 * - `handle`: The scope handle to pop.
 *
 * # Safety
 * `handle` must be a valid, non-null `FfiScopeHandle` pointer.
 */
NvAgentRtStatus nvagentrt_pop_scope(const struct FfiScopeHandle *handle);

/**
 * Emit a named lifecycle event.
 *
 * # Parameters
 * - `name`: Null-terminated event name.
 * - `parent`: Optional parent scope handle, or null.
 * - `data_json`: Optional JSON data payload, or null.
 * - `metadata_json`: Optional JSON metadata payload, or null.
 *
 * # Safety
 * `name` must be a valid C string. Other pointer args may be null.
 */
NvAgentRtStatus nvagentrt_event(const char *name,
                                const struct FfiScopeHandle *parent,
                                const char *data_json,
                                const char *metadata_json);

/**
 * Begin a tool call, running pre-call guardrails and intercepts.
 *
 * # Parameters
 * - `name`: Null-terminated tool name.
 * - `args_json`: Tool arguments as a JSON C string.
 * - `parent`: Optional parent scope handle, or null.
 * - `attributes`: Bitfield of tool attributes.
 * - `data_json`: Optional JSON data, or null.
 * - `metadata_json`: Optional JSON metadata, or null.
 * - `tool_call_id`: Optional external correlation ID for the tool call, or null.
 * - `out`: On success, receives a heap-allocated `FfiToolHandle`.
 *
 * # Safety
 * `name` and `args_json` must be valid C strings. `out` must be non-null.
 */
NvAgentRtStatus nvagentrt_tool_call(const char *name,
                                    const char *args_json,
                                    const struct FfiScopeHandle *parent,
                                    uint32_t attributes,
                                    const char *data_json,
                                    const char *metadata_json,
                                    const char *tool_call_id,
                                    struct FfiToolHandle **out);

/**
 * End a tool call, running post-call guardrails and intercepts.
 *
 * # Parameters
 * - `handle`: The tool handle from `nvagentrt_tool_call`.
 * - `result_json`: Tool result as a JSON C string.
 * - `data_json`: Optional JSON data, or null.
 * - `metadata_json`: Optional JSON metadata, or null.
 *
 * # Safety
 * `handle` and `result_json` must be valid, non-null pointers.
 */
NvAgentRtStatus nvagentrt_tool_call_end(const struct FfiToolHandle *handle,
                                        const char *result_json,
                                        const char *data_json,
                                        const char *metadata_json);

/**
 * Execute a tool call end-to-end: run conditional-execution guardrails (on raw
 * args), then request intercepts, sanitize-request guardrails, execution
 * intercepts, the callback, response intercepts, and sanitize-response
 * guardrails. On rejection, only a standalone Mark event is emitted (no
 * Start/End pair) and `GuardrailRejected` is returned. Blocks the calling
 * thread until completion.
 *
 * # Parameters
 * - `name`: Null-terminated tool name.
 * - `args_json`: Tool arguments as a JSON C string.
 * - `func`: C callback that performs the actual tool execution.
 * - `func_user_data`: Opaque pointer passed to `func`.
 * - `func_free`: Optional destructor for `func_user_data`.
 * - `parent`: Optional parent scope handle, or null.
 * - `attributes`: Bitfield of tool attributes.
 * - `data_json`: Optional JSON data, or null.
 * - `metadata_json`: Optional JSON metadata, or null.
 * - `out`: On success, receives the result as a JSON C string. Caller must free
 *   with `nvagentrt_string_free`.
 *
 * # Safety
 * `name`, `args_json`, and `out` must be valid, non-null pointers.
 */
NvAgentRtStatus nvagentrt_tool_call_execute(const char *name,
                                            const char *args_json,
                                            NvAgentRtToolExecCb func,
                                            void *func_user_data,
                                            NvAgentRtFreeFn func_free,
                                            const struct FfiScopeHandle *parent,
                                            uint32_t attributes,
                                            const char *data_json,
                                            const char *metadata_json,
                                            char **out);

/**
 * Begin an LLM call, running pre-call guardrails and intercepts.
 *
 * # Parameters
 * - `name`: Null-terminated LLM provider name.
 * - `native_json`: The native request payload as a JSON C string.
 * - `parent`: Optional parent scope handle, or null.
 * - `attributes`: Bitfield of LLM attributes.
 * - `data_json`: Optional JSON data, or null.
 * - `metadata_json`: Optional JSON metadata, or null.
 * - `model_name`: Optional LLM model identifier, or null.
 * - `to_request_cb`: Optional callback to convert native JSON to `LLMRequest`, or null.
 * - `to_request_ud`: Opaque pointer passed to `to_request_cb`.
 * - `to_request_free`: Optional destructor for `to_request_ud`.
 * - `out`: On success, receives a heap-allocated `FfiLLMHandle`.
 *
 * # Safety
 * `name`, `native_json`, and `out` must be valid, non-null pointers.
 */
NvAgentRtStatus nvagentrt_llm_call(const char *name,
                                   const char *native_json,
                                   const struct FfiScopeHandle *parent,
                                   uint32_t attributes,
                                   const char *data_json,
                                   const char *metadata_json,
                                   const char *model_name,
                                   struct Option_NvAgentRtJsonCb to_request_cb,
                                   void *to_request_ud,
                                   NvAgentRtFreeFn to_request_free,
                                   struct FfiLLMHandle **out);

/**
 * End an LLM call, running post-call guardrails and intercepts.
 *
 * # Parameters
 * - `handle`: The LLM handle from `nvagentrt_llm_call`.
 * - `response_json`: LLM response as a JSON C string.
 * - `data_json`: Optional JSON data, or null.
 * - `metadata_json`: Optional JSON metadata, or null.
 * - `to_response_cb`: Optional callback to convert native JSON to `LLMResponse`, or null.
 * - `to_response_ud`: Opaque pointer passed to `to_response_cb`.
 * - `to_response_free`: Optional destructor for `to_response_ud`.
 *
 * # Safety
 * `handle` and `response_json` must be valid, non-null pointers.
 */
NvAgentRtStatus nvagentrt_llm_call_end(const struct FfiLLMHandle *handle,
                                       const char *response_json,
                                       const char *data_json,
                                       const char *metadata_json,
                                       struct Option_NvAgentRtJsonCb to_response_cb,
                                       void *to_response_ud,
                                       NvAgentRtFreeFn to_response_free);

/**
 * Execute an LLM call end-to-end: run conditional-execution guardrails (on raw
 * request), then request intercepts, sanitize-request guardrails, execution
 * intercepts, the callback, response intercepts, and sanitize-response
 * guardrails. On rejection, only a standalone Mark event is emitted (no
 * Start/End pair) and `GuardrailRejected` is returned. Blocks the calling
 * thread until completion.
 *
 * # Parameters
 * - `name`: Null-terminated LLM provider name.
 * - `native_json`: The native request payload as a JSON C string.
 * - `func`: C callback that performs the actual LLM call.
 * - `func_user_data`: Opaque pointer passed to `func`.
 * - `func_free`: Optional destructor for `func_user_data`.
 * - `parent`: Optional parent scope handle, or null.
 * - `attributes`: Bitfield of LLM attributes.
 * - `data_json`: Optional JSON data, or null.
 * - `metadata_json`: Optional JSON metadata, or null.
 * - `model_name`: Optional LLM model identifier, or null.
 * - `to_request_cb`: Optional callback to convert native JSON to `LLMRequest`, or null.
 * - `to_request_ud`: Opaque pointer passed to `to_request_cb`.
 * - `to_request_free`: Optional destructor for `to_request_ud`.
 * - `to_response_cb`: Optional callback to convert native JSON to `LLMResponse`, or null.
 * - `to_response_ud`: Opaque pointer passed to `to_response_cb`.
 * - `to_response_free`: Optional destructor for `to_response_ud`.
 * - `out`: On success, receives the response as a JSON C string. Caller must
 *   free with `nvagentrt_string_free`.
 *
 * # Safety
 * `name`, `native_json`, and `out` must be valid, non-null pointers.
 */
NvAgentRtStatus nvagentrt_llm_call_execute(const char *name,
                                           const char *native_json,
                                           NvAgentRtLlmExecCb func,
                                           void *func_user_data,
                                           NvAgentRtFreeFn func_free,
                                           const struct FfiScopeHandle *parent,
                                           uint32_t attributes,
                                           const char *data_json,
                                           const char *metadata_json,
                                           const char *model_name,
                                           struct Option_NvAgentRtJsonCb to_request_cb,
                                           void *to_request_ud,
                                           NvAgentRtFreeFn to_request_free,
                                           struct Option_NvAgentRtJsonCb to_response_cb,
                                           void *to_response_ud,
                                           NvAgentRtFreeFn to_response_free,
                                           char **out);

/**
 * Execute a streaming LLM call end-to-end. Conditional-execution guardrails
 * run first on the raw request. Returns a stream handle that can be polled
 * with `nvagentrt_stream_next`. Blocks until the stream is set up.
 *
 * # Parameters
 * - `name`: Null-terminated LLM provider name.
 * - `native_json`: The native request payload as a JSON C string.
 * - `func`: C callback that performs the actual LLM call.
 * - `func_user_data`: Opaque pointer passed to `func`.
 * - `func_free`: Optional destructor for `func_user_data`.
 * - `collector`: Callback invoked with each intercepted chunk as a JSON string.
 *   May be null, in which case chunks are not collected.
 * - `finalizer`: Callback invoked once when the stream is exhausted to produce
 *   the aggregated response as a JSON C string. May be null, in which case the
 *   finalizer returns `Json::Null`.
 * - `parent`: Optional parent scope handle, or null.
 * - `attributes`: Bitfield of LLM attributes.
 * - `data_json`: Optional JSON data, or null.
 * - `metadata_json`: Optional JSON metadata, or null.
 * - `model_name`: Optional LLM model identifier, or null.
 * - `to_request_cb`: Optional callback to convert native JSON to `LLMRequest`, or null.
 * - `to_request_ud`: Opaque pointer passed to `to_request_cb`.
 * - `to_request_free`: Optional destructor for `to_request_ud`.
 * - `to_response_cb`: Optional callback to convert native JSON to `LLMResponse`, or null.
 * - `to_response_ud`: Opaque pointer passed to `to_response_cb`.
 * - `to_response_free`: Optional destructor for `to_response_ud`.
 * - `out`: On success, receives a heap-allocated `FfiStream`.
 *
 * # Safety
 * `name`, `native_json`, and `out` must be valid, non-null pointers. `collector`
 * and `finalizer` may be null.
 */
NvAgentRtStatus nvagentrt_llm_stream_call_execute(const char *name,
                                                  const char *native_json,
                                                  NvAgentRtLlmExecCb func,
                                                  void *func_user_data,
                                                  NvAgentRtFreeFn func_free,
                                                  struct Option_NvAgentRtCollectorCb collector,
                                                  struct Option_NvAgentRtFinalizerCb finalizer,
                                                  const struct FfiScopeHandle *parent,
                                                  uint32_t attributes,
                                                  const char *data_json,
                                                  const char *metadata_json,
                                                  const char *model_name,
                                                  struct Option_NvAgentRtJsonCb to_request_cb,
                                                  void *to_request_ud,
                                                  NvAgentRtFreeFn to_request_free,
                                                  struct Option_NvAgentRtJsonCb to_response_cb,
                                                  void *to_response_ud,
                                                  NvAgentRtFreeFn to_response_free,
                                                  struct FfiStream **out);

/**
 * Poll the next chunk from a streaming LLM response. Blocks until a chunk is
 * available.
 *
 * # Returns
 * - `1`: A chunk was written to `*out_chunk`. Caller must free with
 *   `nvagentrt_string_free`.
 * - `0`: The stream is complete (no more chunks).
 * - `-1`: An error occurred. Call `nvagentrt_last_error` for details.
 *
 * # Safety
 * `stream` and `out_chunk` must be valid, non-null pointers.
 */
int32_t nvagentrt_stream_next(struct FfiStream *stream, char **out_chunk);

/**
 * Free a stream handle and release its resources.
 *
 * # Safety
 * `stream` must be a valid `FfiStream` pointer returned by
 * `nvagentrt_llm_stream_call_execute`, or null.
 */
void nvagentrt_stream_free(struct FfiStream *stream);

/**
 * Register a tool conditional execution guardrail. The callback decides whether
 * a tool call should proceed. Returns an error message to reject, or null to allow.
 *
 * # Parameters
 * - `name`: Unique guardrail name.
 * - `priority`: Execution priority (lower runs first).
 * - `cb`: Conditional callback.
 * - `user_data`: Opaque pointer passed to `cb`.
 * - `free_fn`: Optional destructor for `user_data`.
 *
 * # Safety
 * `name` must be a valid C string. `cb` must be a valid function pointer.
 */
NvAgentRtStatus nvagentrt_register_tool_conditional_execution_guardrail(const char *name,
                                                                        int32_t priority,
                                                                        NvAgentRtToolConditionalCb cb,
                                                                        void *user_data,
                                                                        NvAgentRtFreeFn free_fn);

/**
 * Deregister a tool conditional execution guardrail by name.
 *
 * # Safety
 * `name` must be a valid C string.
 */
NvAgentRtStatus nvagentrt_deregister_tool_conditional_execution_guardrail(const char *name);

/**
 * Register a tool execution intercept following the middleware chain pattern.
 * When the condition callback returns true, the execution callback is included
 * in the chain. The callback receives `(args, next_fn, next_ctx)` — call
 * `next_fn(args, next_ctx)` to invoke the next intercept or the original
 * tool function, or skip calling it to short-circuit.
 *
 * # Parameters
 * - `name`: Unique intercept name.
 * - `priority`: Execution priority (lower runs first).
 * - `cond_cb`: Condition callback that decides if this intercept applies.
 * - `cond_user_data`: Opaque pointer for the condition callback.
 * - `cond_free`: Optional destructor for `cond_user_data`.
 * - `exec_cb`: Middleware callback receiving args and a next function.
 * - `exec_user_data`: Opaque pointer for the execution callback.
 * - `exec_free`: Optional destructor for `exec_user_data`.
 *
 * # Safety
 * `name` must be a valid C string. Callback pointers must be valid.
 */
NvAgentRtStatus nvagentrt_register_tool_execution_intercept(const char *name,
                                                            int32_t priority,
                                                            NvAgentRtToolExecConditionalCb cond_cb,
                                                            void *cond_user_data,
                                                            NvAgentRtFreeFn cond_free,
                                                            NvAgentRtToolExecInterceptCb exec_cb,
                                                            void *exec_user_data,
                                                            NvAgentRtFreeFn exec_free);

/**
 * Deregister a tool execution intercept by name.
 *
 * # Safety
 * `name` must be a valid C string.
 */
NvAgentRtStatus nvagentrt_deregister_tool_execution_intercept(const char *name);

/**
 * Register an LLM request sanitization guardrail. The callback can modify or
 * replace the LLM request before it is sent.
 *
 * # Parameters
 * - `name`: Unique guardrail name.
 * - `priority`: Execution priority (lower runs first).
 * - `cb`: Request sanitize callback.
 * - `user_data`: Opaque pointer passed to `cb`.
 * - `free_fn`: Optional destructor for `user_data`.
 *
 * # Safety
 * `name` must be a valid C string. `cb` must be a valid function pointer.
 */
NvAgentRtStatus nvagentrt_register_llm_sanitize_request_guardrail(const char *name,
                                                                  int32_t priority,
                                                                  NvAgentRtLlmRequestCb cb,
                                                                  void *user_data,
                                                                  NvAgentRtFreeFn free_fn);

/**
 * Deregister an LLM request sanitization guardrail by name.
 *
 * # Safety
 * `name` must be a valid C string.
 */
NvAgentRtStatus nvagentrt_deregister_llm_sanitize_request_guardrail(const char *name);

/**
 * Register an LLM response sanitization guardrail. The callback can inspect
 * and modify the LLM response after it is received.
 *
 * # Parameters
 * - `name`: Unique guardrail name.
 * - `priority`: Execution priority (lower runs first).
 * - `cb`: JSON-to-JSON callback that receives LLMResponse JSON and returns sanitized JSON.
 * - `user_data`: Opaque pointer passed to `cb`.
 * - `free_fn`: Optional destructor for `user_data`.
 *
 * # Safety
 * `name` must be a valid C string. `cb` must be a valid function pointer.
 */
NvAgentRtStatus nvagentrt_register_llm_sanitize_response_guardrail(const char *name,
                                                                   int32_t priority,
                                                                   NvAgentRtJsonCb cb,
                                                                   void *user_data,
                                                                   NvAgentRtFreeFn free_fn);

/**
 * Deregister an LLM response sanitization guardrail by name.
 *
 * # Safety
 * `name` must be a valid C string.
 */
NvAgentRtStatus nvagentrt_deregister_llm_sanitize_response_guardrail(const char *name);

/**
 * Register an LLM conditional execution guardrail. The callback decides
 * whether an LLM call should proceed.
 *
 * # Parameters
 * - `name`: Unique guardrail name.
 * - `priority`: Execution priority (lower runs first).
 * - `cb`: Conditional callback. Returns null to allow, or error message to reject.
 * - `user_data`: Opaque pointer passed to `cb`.
 * - `free_fn`: Optional destructor for `user_data`.
 *
 * # Safety
 * `name` must be a valid C string. `cb` must be a valid function pointer.
 */
NvAgentRtStatus nvagentrt_register_llm_conditional_execution_guardrail(const char *name,
                                                                       int32_t priority,
                                                                       NvAgentRtLlmConditionalCb cb,
                                                                       void *user_data,
                                                                       NvAgentRtFreeFn free_fn);

/**
 * Deregister an LLM conditional execution guardrail by name.
 *
 * # Safety
 * `name` must be a valid C string.
 */
NvAgentRtStatus nvagentrt_deregister_llm_conditional_execution_guardrail(const char *name);

/**
 * Register an LLM request intercept. The callback can transform the native
 * request JSON before it reaches the LLM provider.
 *
 * # Parameters
 * - `name`: Unique intercept name.
 * - `priority`: Execution priority (lower runs first).
 * - `break_chain`: If true, stop processing further intercepts after this one.
 * - `cb`: JSON transform callback (receives/returns native JSON C string).
 * - `user_data`: Opaque pointer passed to `cb`.
 * - `free_fn`: Optional destructor for `user_data`.
 *
 * # Safety
 * `name` must be a valid C string. `cb` must be a valid function pointer.
 */
NvAgentRtStatus nvagentrt_register_llm_request_intercept(const char *name,
                                                         int32_t priority,
                                                         bool break_chain,
                                                         NvAgentRtJsonCb cb,
                                                         void *user_data,
                                                         NvAgentRtFreeFn free_fn);

/**
 * Deregister an LLM request intercept by name.
 *
 * # Safety
 * `name` must be a valid C string.
 */
NvAgentRtStatus nvagentrt_deregister_llm_request_intercept(const char *name);

/**
 * Register an LLM response intercept. The callback can transform the
 * LLM response after it is received from the LLM provider.
 *
 * # Parameters
 * - `name`: Unique intercept name.
 * - `priority`: Execution priority (lower runs first).
 * - `break_chain`: If true, stop processing further intercepts after this one.
 * - `cb`: JSON transform callback (receives/returns LLMResponse as JSON C string).
 * - `user_data`: Opaque pointer passed to `cb`.
 * - `free_fn`: Optional destructor for `user_data`.
 *
 * # Safety
 * `name` must be a valid C string. `cb` must be a valid function pointer.
 */
NvAgentRtStatus nvagentrt_register_llm_response_intercept(const char *name,
                                                          int32_t priority,
                                                          bool break_chain,
                                                          NvAgentRtJsonCb cb,
                                                          void *user_data,
                                                          NvAgentRtFreeFn free_fn);

/**
 * Deregister an LLM response intercept by name.
 *
 * # Safety
 * `name` must be a valid C string.
 */
NvAgentRtStatus nvagentrt_deregister_llm_response_intercept(const char *name);

/**
 * Register an LLM streaming response intercept. The callback transforms
 * individual chunk strings as they arrive during a streaming LLM call.
 *
 * # Parameters
 * - `name`: Unique intercept name.
 * - `priority`: Execution priority (lower runs first).
 * - `break_chain`: If true, stop processing further intercepts after this one.
 * - `cb`: Chunk string transform callback (receives/returns C string).
 * - `user_data`: Opaque pointer passed to `cb`.
 * - `free_fn`: Optional destructor for `user_data`.
 *
 * # Safety
 * `name` must be a valid C string. `cb` must be a valid function pointer.
 */
NvAgentRtStatus nvagentrt_register_llm_stream_response_intercept(const char *name,
                                                                 int32_t priority,
                                                                 bool break_chain,
                                                                 NvAgentRtSseInterceptCb cb,
                                                                 void *user_data,
                                                                 NvAgentRtFreeFn free_fn);

/**
 * Deregister an LLM streaming response intercept by name.
 *
 * # Safety
 * `name` must be a valid C string.
 */
NvAgentRtStatus nvagentrt_deregister_llm_stream_response_intercept(const char *name);

/**
 * Register an LLM execution intercept following the middleware chain pattern.
 * When the condition callback returns true, the execution callback is included
 * in the chain. The callback receives `(request, next_fn, next_ctx)` — call
 * `next_fn(request, next_ctx)` to invoke the next intercept or the original
 * LLM call, or skip calling it to short-circuit.
 *
 * # Parameters
 * - `name`: Unique intercept name.
 * - `priority`: Execution priority (lower runs first).
 * - `cond_cb`: Condition callback.
 * - `cond_user_data`: Opaque pointer for the condition callback.
 * - `cond_free`: Optional destructor for `cond_user_data`.
 * - `exec_cb`: Middleware callback receiving request and a next function.
 * - `exec_user_data`: Opaque pointer for the execution callback.
 * - `exec_free`: Optional destructor for `exec_user_data`.
 *
 * # Safety
 * `name` must be a valid C string. Callback pointers must be valid.
 */
NvAgentRtStatus nvagentrt_register_llm_execution_intercept(const char *name,
                                                           int32_t priority,
                                                           NvAgentRtLlmExecConditionalCb cond_cb,
                                                           void *cond_user_data,
                                                           NvAgentRtFreeFn cond_free,
                                                           NvAgentRtLlmExecInterceptCb exec_cb,
                                                           void *exec_user_data,
                                                           NvAgentRtFreeFn exec_free);

/**
 * Deregister an LLM execution intercept by name.
 *
 * # Safety
 * `name` must be a valid C string.
 */
NvAgentRtStatus nvagentrt_deregister_llm_execution_intercept(const char *name);

/**
 * Register an LLM streaming execution intercept following the middleware chain
 * pattern. When the condition callback returns true, the execution callback is
 * included in the chain. The callback receives `(request, next_fn, next_ctx)` —
 * call `next_fn(request, next_ctx)` to invoke the next intercept or the original
 * streaming LLM call, or skip calling it to short-circuit.
 *
 * # Parameters
 * - `name`: Unique intercept name.
 * - `priority`: Execution priority (lower runs first).
 * - `cond_cb`: Condition callback.
 * - `cond_user_data`: Opaque pointer for the condition callback.
 * - `cond_free`: Optional destructor for `cond_user_data`.
 * - `exec_cb`: Middleware callback receiving request and a next function.
 * - `exec_user_data`: Opaque pointer for the execution callback.
 * - `exec_free`: Optional destructor for `exec_user_data`.
 *
 * # Safety
 * `name` must be a valid C string. Callback pointers must be valid.
 */
NvAgentRtStatus nvagentrt_register_llm_stream_execution_intercept(const char *name,
                                                                  int32_t priority,
                                                                  NvAgentRtLlmExecConditionalCb cond_cb,
                                                                  void *cond_user_data,
                                                                  NvAgentRtFreeFn cond_free,
                                                                  NvAgentRtLlmExecInterceptCb exec_cb,
                                                                  void *exec_user_data,
                                                                  NvAgentRtFreeFn exec_free);

/**
 * Deregister an LLM streaming execution intercept by name.
 *
 * # Safety
 * `name` must be a valid C string.
 */
NvAgentRtStatus nvagentrt_deregister_llm_stream_execution_intercept(const char *name);

/**
 * Register an event subscriber. The callback is invoked for every lifecycle
 * event emitted by the runtime.
 *
 * # Parameters
 * - `name`: Unique subscriber name.
 * - `cb`: Event callback. The `FfiEvent` is valid only during the call.
 * - `user_data`: Opaque pointer passed to `cb`.
 * - `free_fn`: Optional destructor for `user_data`.
 *
 * # Safety
 * `name` must be a valid C string. `cb` must be a valid function pointer.
 */
NvAgentRtStatus nvagentrt_register_subscriber(const char *name,
                                              NvAgentRtEventSubscriberCb cb,
                                              void *user_data,
                                              NvAgentRtFreeFn free_fn);

/**
 * Deregister an event subscriber by name.
 *
 * # Safety
 * `name` must be a valid C string.
 */
NvAgentRtStatus nvagentrt_deregister_subscriber(const char *name);

/**
 * Create a new isolated scope stack with its own root scope.
 *
 * Each scope stack is independent: scopes pushed on one do not appear on another.
 * Use `nvagentrt_scope_stack_set_thread` to bind a stack to the current thread
 * before making other NVAgentRT API calls.
 *
 * # Parameters
 * - `out`: On success, receives a heap-allocated `FfiScopeStack` that must be
 *   freed with `nvagentrt_scope_stack_free`.
 *
 * # Safety
 * `out` must be a valid, non-null pointer.
 */
NvAgentRtStatus nvagentrt_scope_stack_create(struct FfiScopeStack **out);

/**
 * Bind an isolated scope stack to the current OS thread.
 *
 * After this call, all NVAgentRT scope operations on the current thread
 * (e.g. `nvagentrt_push_scope`, `nvagentrt_get_handle`) will use the
 * given scope stack. This is typically used from Go goroutines that have
 * called `runtime.LockOSThread()`.
 *
 * The `FfiScopeStack` is **not** consumed — the caller retains ownership
 * and must still free it when done.
 *
 * # Safety
 * `stack` must be a valid, non-null `FfiScopeStack` pointer.
 */
NvAgentRtStatus nvagentrt_scope_stack_set_thread(const struct FfiScopeStack *stack);

/**
 * Creates a new ATIF exporter.
 *
 * # Parameters
 * - `session_id`: Session identifier string (required, non-null).
 * - `agent_name`: Agent name string (required, non-null).
 * - `agent_version`: Agent version string (required, non-null).
 * - `model_name`: Default model name (nullable).
 * - `out`: On success, receives a heap-allocated `FfiAtifExporter`.
 *
 * # Safety
 * All non-null string pointers must be valid C strings. `out` must be valid.
 */
NvAgentRtStatus nvagentrt_atif_exporter_create(const char *session_id,
                                               const char *agent_name,
                                               const char *agent_version,
                                               const char *model_name,
                                               struct FfiAtifExporter **out);

/**
 * Registers the exporter as an event subscriber.
 *
 * # Parameters
 * - `exporter`: The exporter handle.
 * - `name`: Subscriber name (required, non-null).
 *
 * # Safety
 * `exporter` and `name` must be valid, non-null pointers.
 */
NvAgentRtStatus nvagentrt_atif_exporter_register(const struct FfiAtifExporter *exporter,
                                                 const char *name);

/**
 * Deregisters the exporter subscriber.
 *
 * # Parameters
 * - `name`: Subscriber name (required, non-null).
 *
 * # Safety
 * `name` must be a valid C string.
 */
NvAgentRtStatus nvagentrt_atif_exporter_deregister(const char *name);

/**
 * Exports collected events as an ATIF trajectory JSON string.
 *
 * # Parameters
 * - `exporter`: The exporter handle.
 * - `root_uuid`: Optional root UUID filter (nullable C string).
 * - `out`: On success, receives a JSON string (caller must free with
 *   `nvagentrt_string_free`).
 *
 * # Safety
 * `exporter` and `out` must be valid, non-null pointers. `root_uuid` may be
 * null.
 */
NvAgentRtStatus nvagentrt_atif_exporter_export(const struct FfiAtifExporter *exporter,
                                               const char *root_uuid,
                                               char **out);

/**
 * Clears all collected events from the exporter.
 *
 * # Parameters
 * - `exporter`: The exporter handle.
 *
 * # Safety
 * `exporter` must be a valid, non-null `FfiAtifExporter` pointer.
 */
NvAgentRtStatus nvagentrt_atif_exporter_clear(const struct FfiAtifExporter *exporter);

/**
 * Run the registered tool request intercept chain on the given arguments.
 *
 * # Parameters
 * - `name`: Tool name (null-terminated C string).
 * - `args_json`: Tool arguments as a JSON C string.
 * - `out`: On success, receives the transformed JSON string (caller must free
 *   with `nvagentrt_string_free`).
 *
 * # Safety
 * All pointers must be valid. `out` must be non-null.
 */
NvAgentRtStatus nvagentrt_tool_request_intercepts(const char *name,
                                                  const char *args_json,
                                                  char **out);

/**
 * Run the registered tool conditional execution guardrail chain.
 *
 * Returns `NvAgentRtStatus::Ok` if all guardrails pass, or
 * `NvAgentRtStatus::GuardrailRejected` if blocked.
 *
 * # Parameters
 * - `name`: Tool name (null-terminated C string).
 * - `args_json`: Tool arguments as a JSON C string.
 *
 * # Safety
 * All pointers must be valid.
 */
NvAgentRtStatus nvagentrt_tool_conditional_execution(const char *name, const char *args_json);

/**
 * Run the registered tool response intercept chain on the given result.
 *
 * # Parameters
 * - `name`: Tool name (null-terminated C string).
 * - `result_json`: Tool result as a JSON C string.
 * - `out`: On success, receives the transformed JSON string (caller must free
 *   with `nvagentrt_string_free`).
 *
 * # Safety
 * All pointers must be valid. `out` must be non-null.
 */
NvAgentRtStatus nvagentrt_tool_response_intercepts(const char *name,
                                                   const char *result_json,
                                                   char **out);

/**
 * Run the registered LLM request intercept chain on the given native request.
 *
 * # Parameters
 * - `native_json`: Native LLM request as a JSON C string.
 * - `out`: On success, receives the transformed JSON string (caller must free
 *   with `nvagentrt_string_free`).
 *
 * # Safety
 * All pointers must be valid. `out` must be non-null.
 */
NvAgentRtStatus nvagentrt_llm_request_intercepts(const char *native_json, char **out);

/**
 * Run the registered LLM conditional execution guardrail chain.
 *
 * Returns `NvAgentRtStatus::Ok` if all guardrails pass, or
 * `NvAgentRtStatus::GuardrailRejected` if blocked.
 *
 * # Parameters
 * - `native_json`: Native LLM request as a JSON C string.
 * - `to_request_cb`: Optional callback to convert native JSON to `LLMRequest`, or null.
 * - `to_request_ud`: Opaque pointer passed to `to_request_cb`.
 * - `to_request_free`: Optional destructor for `to_request_ud`.
 *
 * # Safety
 * All pointers must be valid.
 */
NvAgentRtStatus nvagentrt_llm_conditional_execution(const char *native_json,
                                                    struct Option_NvAgentRtJsonCb to_request_cb,
                                                    void *to_request_ud,
                                                    NvAgentRtFreeFn to_request_free);

/**
 * Run the registered LLM response intercept chain on the given response.
 *
 * # Parameters
 * - `response_json`: LLM response as a JSON C string (serialized LLMResponse).
 * - `out`: On success, receives the transformed JSON string (caller must free
 *   with `nvagentrt_string_free`).
 *
 * # Safety
 * All pointers must be valid. `out` must be non-null.
 */
NvAgentRtStatus nvagentrt_llm_response_intercepts(const char *response_json, char **out);

/**
 * Free a C string previously returned by any `nvagentrt_*` accessor function.
 * Passing null is a safe no-op.
 *
 * # Safety
 * `ptr` must be a pointer returned by this library, or null. Double-free is
 * undefined behavior.
 */
void nvagentrt_string_free(char *ptr);

/**
 * Retrieve the last error message set on this thread, or null if no error
 * has occurred since the last [`clear_last_error`] call.
 *
 * The returned pointer borrows from thread-local storage and is valid only
 * until the next FFI call on the same thread. Do **not** free the returned
 * pointer.
 */
const char *nvagentrt_last_error(void);

/**
 * Free a scope handle previously returned by the runtime.
 *
 * # Safety
 * `ptr` must be a valid pointer returned by an `nvagentrt_*` function, or null.
 */
void nvagentrt_scope_handle_free(struct FfiScopeHandle *ptr);

/**
 * Free a tool handle previously returned by the runtime.
 *
 * # Safety
 * `ptr` must be a valid pointer returned by an `nvagentrt_*` function, or null.
 */
void nvagentrt_tool_handle_free(struct FfiToolHandle *ptr);

/**
 * Free an LLM handle previously returned by the runtime.
 *
 * # Safety
 * `ptr` must be a valid pointer returned by an `nvagentrt_*` function, or null.
 */
void nvagentrt_llm_handle_free(struct FfiLLMHandle *ptr);

/**
 * Free an LLM request object.
 *
 * # Safety
 * `ptr` must be a valid pointer returned by an `nvagentrt_*` function, or null.
 */
void nvagentrt_llm_request_free(struct FfiLLMRequest *ptr);

/**
 * Free an event object.
 *
 * # Safety
 * `ptr` must be a valid pointer returned by an `nvagentrt_*` function, or null.
 */
void nvagentrt_event_free(struct FfiEvent *ptr);

/**
 * Free a scope stack handle previously returned by `nvagentrt_scope_stack_create`.
 *
 * # Safety
 * `ptr` must be a valid pointer returned by `nvagentrt_scope_stack_create`, or null.
 */
void nvagentrt_scope_stack_free(struct FfiScopeStack *ptr);

/**
 * Free an ATIF exporter handle previously returned by `nvagentrt_atif_exporter_create`.
 *
 * # Safety
 * `ptr` must be a valid pointer returned by `nvagentrt_atif_exporter_create`, or null.
 */
void nvagentrt_atif_exporter_free(struct FfiAtifExporter *ptr);

/**
 * Return the UUID of a scope handle as a C string. Caller must free the result
 * with `nvagentrt_string_free`. Returns null if `ptr` is null.
 *
 * # Safety
 * `ptr` must be a valid `FfiScopeHandle` pointer or null.
 */
char *nvagentrt_scope_handle_uuid(const struct FfiScopeHandle *ptr);

/**
 * Return the name of a scope handle as a C string. Caller must free the result.
 * Returns null if `ptr` is null.
 *
 * # Safety
 * `ptr` must be a valid `FfiScopeHandle` pointer or null.
 */
char *nvagentrt_scope_handle_name(const struct FfiScopeHandle *ptr);

/**
 * Return the scope type of a scope handle. Returns `Unknown` if `ptr` is null.
 *
 * # Safety
 * `ptr` must be a valid `FfiScopeHandle` pointer or null.
 */
NvAgentRtScopeType nvagentrt_scope_handle_scope_type(const struct FfiScopeHandle *ptr);

/**
 * Return the bitfield attributes of a scope handle. Returns 0 if `ptr` is null.
 *
 * # Safety
 * `ptr` must be a valid `FfiScopeHandle` pointer or null.
 */
uint32_t nvagentrt_scope_handle_attributes(const struct FfiScopeHandle *ptr);

/**
 * Return the parent scope UUID as a C string, or null if there is no parent.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiScopeHandle` pointer or null.
 */
char *nvagentrt_scope_handle_parent_uuid(const struct FfiScopeHandle *ptr);

/**
 * Return the scope data as a JSON C string, or null if no data is set.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiScopeHandle` pointer or null.
 */
char *nvagentrt_scope_handle_data(const struct FfiScopeHandle *ptr);

/**
 * Return the scope metadata as a JSON C string, or null if no metadata is set.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiScopeHandle` pointer or null.
 */
char *nvagentrt_scope_handle_metadata(const struct FfiScopeHandle *ptr);

/**
 * Return the UUID of a tool handle as a C string. Caller must free the result.
 *
 * # Safety
 * `ptr` must be a valid `FfiToolHandle` pointer or null.
 */
char *nvagentrt_tool_handle_uuid(const struct FfiToolHandle *ptr);

/**
 * Return the name of a tool handle as a C string. Caller must free the result.
 *
 * # Safety
 * `ptr` must be a valid `FfiToolHandle` pointer or null.
 */
char *nvagentrt_tool_handle_name(const struct FfiToolHandle *ptr);

/**
 * Return the bitfield attributes of a tool handle. Returns 0 if `ptr` is null.
 *
 * # Safety
 * `ptr` must be a valid `FfiToolHandle` pointer or null.
 */
uint32_t nvagentrt_tool_handle_attributes(const struct FfiToolHandle *ptr);

/**
 * Return the parent scope UUID of a tool handle, or null if none.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiToolHandle` pointer or null.
 */
char *nvagentrt_tool_handle_parent_uuid(const struct FfiToolHandle *ptr);

/**
 * Return the UUID of an LLM handle as a C string. Caller must free the result.
 *
 * # Safety
 * `ptr` must be a valid `FfiLLMHandle` pointer or null.
 */
char *nvagentrt_llm_handle_uuid(const struct FfiLLMHandle *ptr);

/**
 * Return the name of an LLM handle as a C string. Caller must free the result.
 *
 * # Safety
 * `ptr` must be a valid `FfiLLMHandle` pointer or null.
 */
char *nvagentrt_llm_handle_name(const struct FfiLLMHandle *ptr);

/**
 * Return the bitfield attributes of an LLM handle. Returns 0 if `ptr` is null.
 *
 * # Safety
 * `ptr` must be a valid `FfiLLMHandle` pointer or null.
 */
uint32_t nvagentrt_llm_handle_attributes(const struct FfiLLMHandle *ptr);

/**
 * Return the parent scope UUID of an LLM handle, or null if none.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiLLMHandle` pointer or null.
 */
char *nvagentrt_llm_handle_parent_uuid(const struct FfiLLMHandle *ptr);

/**
 * Create a new LLM request object. Returns a heap-allocated `FfiLLMRequest`
 * that must be freed with `nvagentrt_llm_request_free`. Returns null on
 * invalid input.
 *
 * # Parameters
 * - `headers_json`: JSON object of headers/metadata, or null.
 * - `content_json`: JSON request content payload, or null.
 *
 * # Safety
 * All string arguments must be valid null-terminated C strings or null.
 */
struct FfiLLMRequest *nvagentrt_llm_request_new(const char *headers_json, const char *content_json);

/**
 * Return the headers of an LLM request as a JSON C string. Caller must free the result.
 *
 * # Safety
 * `ptr` must be a valid `FfiLLMRequest` pointer or null.
 */
char *nvagentrt_llm_request_headers(const struct FfiLLMRequest *ptr);

/**
 * Return the content of an LLM request as a JSON C string. Caller must free the result.
 *
 * # Safety
 * `ptr` must be a valid `FfiLLMRequest` pointer or null.
 */
char *nvagentrt_llm_request_content(const struct FfiLLMRequest *ptr);

/**
 * Free an LLM response object.
 *
 * # Safety
 * `ptr` must be a valid pointer returned by an `nvagentrt_*` function, or null.
 */
void nvagentrt_llm_response_free(struct FfiLLMResponse *ptr);

/**
 * Return the data of an LLM response as a JSON C string. Caller must free the result.
 *
 * # Safety
 * `ptr` must be a valid `FfiLLMResponse` pointer or null.
 */
char *nvagentrt_llm_response_data(const struct FfiLLMResponse *ptr);

/**
 * Return the UUID of an event as a C string. Caller must free the result.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
char *nvagentrt_event_uuid(const struct FfiEvent *ptr);

/**
 * Return the name of an event as a C string, or null if unnamed.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
char *nvagentrt_event_name(const struct FfiEvent *ptr);

/**
 * Return the event type. Returns `Mark` if `ptr` is null.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
NvAgentRtEventType nvagentrt_event_type(const struct FfiEvent *ptr);

/**
 * Return the event data as a JSON C string, or null if no data is set.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
char *nvagentrt_event_data(const struct FfiEvent *ptr);

/**
 * Return the event metadata as a JSON C string, or null if no metadata is set.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
char *nvagentrt_event_metadata(const struct FfiEvent *ptr);

/**
 * Return the event timestamp as an RFC 3339 C string. Caller must free the result.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
char *nvagentrt_event_timestamp(const struct FfiEvent *ptr);

/**
 * Return the event input as a JSON C string, or null if no input is set.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
char *nvagentrt_event_input(const struct FfiEvent *ptr);

/**
 * Return the event output as a JSON C string, or null if no output is set.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
char *nvagentrt_event_output(const struct FfiEvent *ptr);

/**
 * Return the event model name as a C string, or null if no model name is set.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
char *nvagentrt_event_model_name(const struct FfiEvent *ptr);

/**
 * Return the event tool call ID as a C string, or null if no tool call ID is set.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
char *nvagentrt_event_tool_call_id(const struct FfiEvent *ptr);

/**
 * Return the event root UUID as a C string, or null if no root UUID is set.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
char *nvagentrt_event_root_uuid(const struct FfiEvent *ptr);

/**
 * Return the event parent UUID as a C string, or null if no parent UUID is set.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
char *nvagentrt_event_parent_uuid(const struct FfiEvent *ptr);

/**
 * Return the event scope type as a C string, or null if no scope type is set.
 * Caller must free the result with `nvagentrt_string_free`.
 *
 * # Safety
 * `ptr` must be a valid `FfiEvent` pointer or null.
 */
char *nvagentrt_event_scope_type(const struct FfiEvent *ptr);

#endif  /* NVAGENTRT_H */
