# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import plugin_worker_pb2 as plugin__worker__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginWorkerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
                '/nemo.relay.worker.v1.PluginWorker/Handshake',
                request_serializer=plugin__worker__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/nemo.relay.worker.v1.PluginWorker/Health',
                request_serializer=plugin__worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Validate = channel.unary_unary(
                '/nemo.relay.worker.v1.PluginWorker/Validate',
                request_serializer=plugin__worker__pb2.ValidateRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/nemo.relay.worker.v1.PluginWorker/Register',
                request_serializer=plugin__worker__pb2.RegisterRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/nemo.relay.worker.v1.PluginWorker/Invoke',
                request_serializer=plugin__worker__pb2.InvokeRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.InvokeResponse.FromString,
                _registered_method=True)
        self.InvokeStream = channel.unary_stream(
                '/nemo.relay.worker.v1.PluginWorker/InvokeStream',
                request_serializer=plugin__worker__pb2.InvokeRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.StreamChunk.FromString,
                _registered_method=True)
        self.CancelInvocation = channel.unary_unary(
                '/nemo.relay.worker.v1.PluginWorker/CancelInvocation',
                request_serializer=plugin__worker__pb2.CancelInvocationRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.WorkerAck.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/nemo.relay.worker.v1.PluginWorker/Shutdown',
                request_serializer=plugin__worker__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.WorkerAck.FromString,
                _registered_method=True)


class PluginWorkerServicer:
    """Missing associated documentation comment in .proto file."""

    def Handshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Validate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelInvocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=plugin__worker__pb2.HandshakeRequest.FromString,
                    response_serializer=plugin__worker__pb2.HandshakeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=plugin__worker__pb2.HealthRequest.FromString,
                    response_serializer=plugin__worker__pb2.HealthResponse.SerializeToString,
            ),
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=plugin__worker__pb2.ValidateRequest.FromString,
                    response_serializer=plugin__worker__pb2.ValidateResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=plugin__worker__pb2.RegisterRequest.FromString,
                    response_serializer=plugin__worker__pb2.RegisterResponse.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=plugin__worker__pb2.InvokeRequest.FromString,
                    response_serializer=plugin__worker__pb2.InvokeResponse.SerializeToString,
            ),
            'InvokeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.InvokeStream,
                    request_deserializer=plugin__worker__pb2.InvokeRequest.FromString,
                    response_serializer=plugin__worker__pb2.StreamChunk.SerializeToString,
            ),
            'CancelInvocation': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelInvocation,
                    request_deserializer=plugin__worker__pb2.CancelInvocationRequest.FromString,
                    response_serializer=plugin__worker__pb2.WorkerAck.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=plugin__worker__pb2.ShutdownRequest.FromString,
                    response_serializer=plugin__worker__pb2.WorkerAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nemo.relay.worker.v1.PluginWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nemo.relay.worker.v1.PluginWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginWorker:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.PluginWorker/Handshake',
            plugin__worker__pb2.HandshakeRequest.SerializeToString,
            plugin__worker__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.PluginWorker/Health',
            plugin__worker__pb2.HealthRequest.SerializeToString,
            plugin__worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.PluginWorker/Validate',
            plugin__worker__pb2.ValidateRequest.SerializeToString,
            plugin__worker__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.PluginWorker/Register',
            plugin__worker__pb2.RegisterRequest.SerializeToString,
            plugin__worker__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.PluginWorker/Invoke',
            plugin__worker__pb2.InvokeRequest.SerializeToString,
            plugin__worker__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nemo.relay.worker.v1.PluginWorker/InvokeStream',
            plugin__worker__pb2.InvokeRequest.SerializeToString,
            plugin__worker__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelInvocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.PluginWorker/CancelInvocation',
            plugin__worker__pb2.CancelInvocationRequest.SerializeToString,
            plugin__worker__pb2.WorkerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.PluginWorker/Shutdown',
            plugin__worker__pb2.ShutdownRequest.SerializeToString,
            plugin__worker__pb2.WorkerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RelayHostRuntimeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmitMark = channel.unary_unary(
                '/nemo.relay.worker.v1.RelayHostRuntime/EmitMark',
                request_serializer=plugin__worker__pb2.EmitMarkRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.HostAck.FromString,
                _registered_method=True)
        self.PushScope = channel.unary_unary(
                '/nemo.relay.worker.v1.RelayHostRuntime/PushScope',
                request_serializer=plugin__worker__pb2.PushScopeRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.PushScopeResponse.FromString,
                _registered_method=True)
        self.PopScope = channel.unary_unary(
                '/nemo.relay.worker.v1.RelayHostRuntime/PopScope',
                request_serializer=plugin__worker__pb2.PopScopeRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.HostAck.FromString,
                _registered_method=True)
        self.CreateScopeStack = channel.unary_unary(
                '/nemo.relay.worker.v1.RelayHostRuntime/CreateScopeStack',
                request_serializer=plugin__worker__pb2.CreateScopeStackRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.CreateScopeStackResponse.FromString,
                _registered_method=True)
        self.DropScopeStack = channel.unary_unary(
                '/nemo.relay.worker.v1.RelayHostRuntime/DropScopeStack',
                request_serializer=plugin__worker__pb2.DropScopeStackRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.HostAck.FromString,
                _registered_method=True)
        self.ToolNext = channel.unary_unary(
                '/nemo.relay.worker.v1.RelayHostRuntime/ToolNext',
                request_serializer=plugin__worker__pb2.ToolNextRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.JsonResult.FromString,
                _registered_method=True)
        self.LlmNext = channel.unary_unary(
                '/nemo.relay.worker.v1.RelayHostRuntime/LlmNext',
                request_serializer=plugin__worker__pb2.LlmNextRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.JsonResult.FromString,
                _registered_method=True)
        self.LlmStreamNext = channel.unary_stream(
                '/nemo.relay.worker.v1.RelayHostRuntime/LlmStreamNext',
                request_serializer=plugin__worker__pb2.LlmStreamNextRequest.SerializeToString,
                response_deserializer=plugin__worker__pb2.StreamChunk.FromString,
                _registered_method=True)


class RelayHostRuntimeServicer:
    """Missing associated documentation comment in .proto file."""

    def EmitMark(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushScope(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PopScope(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateScopeStack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropScopeStack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToolNext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LlmNext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LlmStreamNext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayHostRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmitMark': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitMark,
                    request_deserializer=plugin__worker__pb2.EmitMarkRequest.FromString,
                    response_serializer=plugin__worker__pb2.HostAck.SerializeToString,
            ),
            'PushScope': grpc.unary_unary_rpc_method_handler(
                    servicer.PushScope,
                    request_deserializer=plugin__worker__pb2.PushScopeRequest.FromString,
                    response_serializer=plugin__worker__pb2.PushScopeResponse.SerializeToString,
            ),
            'PopScope': grpc.unary_unary_rpc_method_handler(
                    servicer.PopScope,
                    request_deserializer=plugin__worker__pb2.PopScopeRequest.FromString,
                    response_serializer=plugin__worker__pb2.HostAck.SerializeToString,
            ),
            'CreateScopeStack': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateScopeStack,
                    request_deserializer=plugin__worker__pb2.CreateScopeStackRequest.FromString,
                    response_serializer=plugin__worker__pb2.CreateScopeStackResponse.SerializeToString,
            ),
            'DropScopeStack': grpc.unary_unary_rpc_method_handler(
                    servicer.DropScopeStack,
                    request_deserializer=plugin__worker__pb2.DropScopeStackRequest.FromString,
                    response_serializer=plugin__worker__pb2.HostAck.SerializeToString,
            ),
            'ToolNext': grpc.unary_unary_rpc_method_handler(
                    servicer.ToolNext,
                    request_deserializer=plugin__worker__pb2.ToolNextRequest.FromString,
                    response_serializer=plugin__worker__pb2.JsonResult.SerializeToString,
            ),
            'LlmNext': grpc.unary_unary_rpc_method_handler(
                    servicer.LlmNext,
                    request_deserializer=plugin__worker__pb2.LlmNextRequest.FromString,
                    response_serializer=plugin__worker__pb2.JsonResult.SerializeToString,
            ),
            'LlmStreamNext': grpc.unary_stream_rpc_method_handler(
                    servicer.LlmStreamNext,
                    request_deserializer=plugin__worker__pb2.LlmStreamNextRequest.FromString,
                    response_serializer=plugin__worker__pb2.StreamChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nemo.relay.worker.v1.RelayHostRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nemo.relay.worker.v1.RelayHostRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RelayHostRuntime:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EmitMark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.RelayHostRuntime/EmitMark',
            plugin__worker__pb2.EmitMarkRequest.SerializeToString,
            plugin__worker__pb2.HostAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushScope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.RelayHostRuntime/PushScope',
            plugin__worker__pb2.PushScopeRequest.SerializeToString,
            plugin__worker__pb2.PushScopeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PopScope(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.RelayHostRuntime/PopScope',
            plugin__worker__pb2.PopScopeRequest.SerializeToString,
            plugin__worker__pb2.HostAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateScopeStack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.RelayHostRuntime/CreateScopeStack',
            plugin__worker__pb2.CreateScopeStackRequest.SerializeToString,
            plugin__worker__pb2.CreateScopeStackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropScopeStack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.RelayHostRuntime/DropScopeStack',
            plugin__worker__pb2.DropScopeStackRequest.SerializeToString,
            plugin__worker__pb2.HostAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToolNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.RelayHostRuntime/ToolNext',
            plugin__worker__pb2.ToolNextRequest.SerializeToString,
            plugin__worker__pb2.JsonResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LlmNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nemo.relay.worker.v1.RelayHostRuntime/LlmNext',
            plugin__worker__pb2.LlmNextRequest.SerializeToString,
            plugin__worker__pb2.JsonResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LlmStreamNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/nemo.relay.worker.v1.RelayHostRuntime/LlmStreamNext',
            plugin__worker__pb2.LlmStreamNextRequest.SerializeToString,
            plugin__worker__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
