# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from dataclasses import dataclass
from typing import Literal, TypedDict

from nemo_flow import JsonObject, UnsupportedBehavior

class ConfigDiagnostic(TypedDict, total=False):
    level: Literal["warning", "error"]
    code: str
    component: str
    field: str
    message: str

class ConfigReport(TypedDict):
    diagnostics: list[ConfigDiagnostic]

@dataclass(slots=True)
class ConfigPolicy:
    unknown_component: UnsupportedBehavior = ...
    unknown_field: UnsupportedBehavior = ...
    unsupported_value: UnsupportedBehavior = ...
    def to_dict(self) -> JsonObject: ...

@dataclass(slots=True)
class BackendSpec:
    kind: str
    config: JsonObject = ...
    @staticmethod
    def in_memory() -> "BackendSpec": ...
    @staticmethod
    def redis(url: str, key_prefix: str = ...) -> "BackendSpec": ...
    def to_dict(self) -> JsonObject: ...

@dataclass(slots=True)
class StateConfig:
    backend: BackendSpec
    def to_dict(self) -> JsonObject: ...

@dataclass(slots=True)
class TelemetryConfig:
    subscriber_name: str | None = ...
    learners: list[str] = ...
    def to_dict(self) -> JsonObject: ...

@dataclass(slots=True)
class AdaptiveHintsConfig:
    priority: int = ...
    break_chain: bool = ...
    inject_header: bool = ...
    inject_body_path: str = ...
    def to_dict(self) -> JsonObject: ...

@dataclass(slots=True)
class ToolParallelismConfig:
    priority: int = ...
    mode: Literal["observe_only", "inject_hints", "schedule"] = ...
    def to_dict(self) -> JsonObject: ...

@dataclass(slots=True)
class AdaptiveConfig:
    version: int = ...
    agent_id: str | None = ...
    state: StateConfig | None = ...
    telemetry: TelemetryConfig | None = ...
    adaptive_hints: AdaptiveHintsConfig | None = ...
    tool_parallelism: ToolParallelismConfig | None = ...
    policy: ConfigPolicy = ...
    def to_dict(self) -> JsonObject: ...

ADAPTIVE_PLUGIN_KIND: Literal["adaptive"]

@dataclass(slots=True)
class ComponentSpec:
    config: AdaptiveConfig | JsonObject
    enabled: bool = ...
    def to_dict(self) -> JsonObject: ...

def set_latency_sensitivity(level: int) -> None: ...
